FROM node:24-alpine AS base

FROM base AS workspace
RUN apk add --no-cache libc6-compat
RUN corepack enable pnpm

FROM workspace AS dependencies
WORKDIR /app
COPY ./proxy-server .
RUN --mount=type=cache,target=/pnpm/store \
    pnpm install --frozen-lockfile
CMD ["node", "./proxy.js"]
